version: "3.8"

services:
  n8n:
    build: .
    image: n8n-custom
    container_name: n8n
    ports:
      - "${port}:${port}"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${username}
      - N8N_BASIC_AUTH_PASSWORD=${password}
      - N8N_HOST=${host}
      - N8N_PORT=${port}
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://${host}/
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: always